version: '3.8'

services:
  n8n-arabic:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    volumes:
      - ./database:/app/database
      - ./logs:/app/logs
    restart: unless-stopped
    networks:
      - n8n-network

networks:
  n8n-network:
    driver: bridge